"""Market data interfaces, normalization, and local providers."""

from __future__ import annotations

from .alpaca import (
    ALPACA_BAR_TIMEFRAMES,
    BAR_FIELDNAMES,
    DEFAULT_OUTPUT_DIRECTORY,
    DEFAULT_OUTPUT_FILENAME_TEMPLATE,
    DEFAULT_PARTITION_BY,
    DEFAULT_SESSION_END,
    DEFAULT_SESSION_START,
    DEFAULT_SESSION_TIMEZONE,
    OUTPUT_FORMATS,
    OUTPUT_LAYOUTS,
    PARTITION_FIELDS,
    SUPPORTED_ALPACA_BAR_TIMEFRAMES,
    AlpacaBarDownloadConfig,
    AlpacaBarDownloadResult,
    AlpacaDataTransport,
    AlpacaMarketDataClient,
    AlpacaSessionFilterConfig,
    UrllibAlpacaDataTransport,
    download_alpaca_bars,
    download_alpaca_bars_to_csv,
    filter_alpaca_session_rows,
    normalize_alpaca_bar_timeframe,
    normalize_output_layout,
    normalize_output_format,
    resolve_alpaca_output_path,
    write_alpaca_bar_rows,
)
from .interfaces import DataPortal, MarketDataProvider
from .normalization import (
    OPTIONAL_BAR_COLUMNS,
    REQUIRED_BAR_COLUMNS,
    filter_bars,
    read_csv_rows,
    row_to_bar,
    rows_to_bars,
    validate_bar_columns,
)
from .portal import DefaultDataPortal
from .providers import (
    BaseHistoricalBarProvider,
    CSVBarProvider,
    LocalParquetProvider,
    ReplayMarketDataProvider,
)
from .streaming import (
    ALPACA_STREAM_FEEDS,
    ALPACA_STREAM_PROVIDERS,
    STREAM_EVENT_TYPES,
    AlpacaStreamClient,
    AlpacaStreamEventSource,
    InMemoryAlpacaStreamClient,
    alpaca_stream_event_source_from_config,
    alpaca_stream_message_to_event,
    normalize_alpaca_stream_feed,
    normalize_stream_event_types,
)

__all__ = [
    "ALPACA_STREAM_FEEDS",
    "ALPACA_STREAM_PROVIDERS",
    "BaseHistoricalBarProvider",
    "ALPACA_BAR_TIMEFRAMES",
    "AlpacaBarDownloadConfig",
    "AlpacaBarDownloadResult",
    "AlpacaDataTransport",
    "AlpacaMarketDataClient",
    "BAR_FIELDNAMES",
    "CSVBarProvider",
    "DEFAULT_OUTPUT_DIRECTORY",
    "DEFAULT_OUTPUT_FILENAME_TEMPLATE",
    "DEFAULT_PARTITION_BY",
    "DEFAULT_SESSION_END",
    "DEFAULT_SESSION_START",
    "DEFAULT_SESSION_TIMEZONE",
    "DataPortal",
    "DefaultDataPortal",
    "LocalParquetProvider",
    "MarketDataProvider",
    "OPTIONAL_BAR_COLUMNS",
    "OUTPUT_FORMATS",
    "OUTPUT_LAYOUTS",
    "PARTITION_FIELDS",
    "REQUIRED_BAR_COLUMNS",
    "ReplayMarketDataProvider",
    "STREAM_EVENT_TYPES",
    "SUPPORTED_ALPACA_BAR_TIMEFRAMES",
    "AlpacaSessionFilterConfig",
    "AlpacaStreamClient",
    "AlpacaStreamEventSource",
    "InMemoryAlpacaStreamClient",
    "UrllibAlpacaDataTransport",
    "alpaca_stream_event_source_from_config",
    "alpaca_stream_message_to_event",
    "download_alpaca_bars",
    "download_alpaca_bars_to_csv",
    "filter_alpaca_session_rows",
    "filter_bars",
    "normalize_alpaca_bar_timeframe",
    "normalize_output_layout",
    "normalize_output_format",
    "normalize_alpaca_stream_feed",
    "normalize_stream_event_types",
    "read_csv_rows",
    "resolve_alpaca_output_path",
    "row_to_bar",
    "rows_to_bars",
    "validate_bar_columns",
    "write_alpaca_bar_rows",
]
